### ISSUE TITLE
Deprecate Puppet 3.X Support

### ISSUE THREAD

**Issue by petems** [voxpupuli/puppet-redis#152]
Puppet 3.X is EOL

So, we want to upgrade this module to have Puppet 4 support.

- [ ]  Create a last release tag in the major version
- [x]  Add notes to the README/add warning to the code for the deprecation
- [ ]  Make a new release, and add types to parameters (Puppet 4 only feature)
- [ ]  Update module to use the new Puppet Lookup/Data in modules work from Puppet 4 onwards

**Comment by v6** [comment]
// , How will those of us poor folk still stuck with Puppet 3 continue to use this? Shall we just install the older version that supports Puppet 3?

**Comment by v6** [comment]
// , If we do use that older version, can we be assured that it will use versions of its dependencies that also work with Puppet 3?

**Comment by petems** [comment]
There will be a final tag for the Puppet 3 features, so you can fork from that tag and continue to support Puppet 3 from that tag. 

The dependancy modules are pinned to versions that support Puppet 3, so the other module dependancies shouldn't be an issue:

```json
{"name":"puppetlabs/apt","version_requirement":">= 2.3.0 <3.0.0"},
{"name":"puppetlabs/stdlib","version_requirement":">= 1.0.2 <5.0.0"},
{"name":"stahnma/epel","version_requirement":">= 1.0.2 <2.0.0"}
```

I would recomend upgrading to Puppet 4 however 😄

**Comment by v6** [comment]
// , Establishing good habits of "software life cycle management", e.g. not using End of Life infrastructure, with people who don't want it can be a struggle, sometimes.

**Comment by petems** [comment]
Done in https://github.com/voxpupuli/puppet-redis/commit/f14f07db1be7b1ded2cd7ac233d43bdd5e3681db

**Comment by v6** [comment]
Is that the "final tag" you alluded to earlier?
