### ISSUE TITLE
Undefined variable 'redis_server_version' warning on first run

### ISSUE THREAD

**Issue by benh57** [voxpupuli/puppet-redis#227]
When this module first runs to install redis, the fact is undefined:  (because it's not installed yet) - Puppet 4 or later warns about this:
 Warning: Undefined variable 'redis_server_version';   (file & line not available)

After the first run, the warning goes away.  To avoid this the fact should be defined to something, even undef might be fine.

**Comment by TheMeier** [comment]
Actuall this leads to errors for me

`Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, integer 7089836968 too big to convert to `int'`


Any chances to cut a release, theres 24 commits merged already on master an the last release was ~6 month ago :/

**Comment by petems** [comment]
Hi @TheMeier! I'm having issues with releasing right now (See https://github.com/arioch/puppet-redis/issues/262) 

But I'm curious, there's no reason that the value should be that big an integer!

Can you run the following on the machine running that: `redis-server -v` and comment the full output into this issue?

**Comment by ekohl** [comment]
I don't think this is an issue anymore so I'm closing this. Feel free to reopen if it persists.
