### ISSUE TITLE
Unable to unset unixsocket config parameter

### ISSUE THREAD

**Issue by benh57** [voxpupuli/puppet-redis#228]
If i spin up a redis like:

```puppet
class { '::redis': 
   unixsocket => undef
}
```

the unixsocket gets set to the default, `/var/run/redis/redis.sock`

Redis 4 doesn't make the `/var/run/redis/` folder by default on Centos 7 so this breaks redis4 out of the box with this module.

Redis has a lot of parameters that do different things if it's not set at all ('bind' is another example, if you want to listen on all interfaces but not pass 0.0.0.0, you just don't list it), so this module should support this.

**Comment by petems** [comment]
Good point, this was done as part of the instance work recently.

Curious though: who's providing Redis 4 for CentOS? The service file should have `RuntimeDirectory=redis` in it, then the directory is created on boot. But that's a different thing

**Comment by petems** [comment]
Is this using the Remi repo? https://rpms.remirepo.net/

**Comment by benh57** [comment]
The dir missing could theoretically be my fault - i'm using a slightly modified spec file, but its taken from the remi repo build scripts.

**Comment by benh57** [comment]
https://github.com/benh57/remirepo/commit/90f2ba5098e40c27b665a6b2339348ad6bf440bf

**Comment by benh57** [comment]
Yeah, looks like my service file doesnt have that, probably cause my remirepo is out of date. Still, we should be able to unset the unixsocket parameter if one doesn't want to enable them. Maybe setting it to 'absent' could make the module unset it in the template?

**Comment by benh57** [comment]
Just recloned their cgit to github at https://github.com/benh57/remirepo_redis , gonna try that version which should fix the socket folder.

**Comment by alexskr** [comment]
looks like this is fixed if you set  `unixsocket => false`

**Comment by ekohl** [comment]
This has changed to the empty string in Redis 5.0.0 but before could be done using `false`.
