### ISSUE TITLE
[Feature Request] Add `rename-command`

### ISSUE THREAD

**Issue by tomer-amir-vonage** [voxpupuli/puppet-redis#242]
Hi,

I am working on making my redis instances production ready and as [Redis themselves](https://redis.io/topics/security) recommend, and [other sources](https://www.digitalocean.com/community/tutorials/how-to-secure-your-redis-installation-on-ubuntu-14-04) as well, you should disable some commands on your production instances.

To do this you need to use the `rename-command` configuration in the config file.

Currently, I did not see that there is a way to do this using this module, but I did find a workaround by including an external config file. I think it would be better if there was a map that I could pass to this module with all the commands and their new names (which could be empty strings if I want to disable them).

Thanks!

**Comment by petems** [comment]
Hi @TomerAmirV!

Cool, any configuration recommendations directly from Redis themselves we want to have in the module, so I'll probably work on this as the next feature to add to the module 👍
