### ISSUE TITLE
Type forking causes service timeout

### ISSUE THREAD

**Issue by dandunckelman** [voxpupuli/puppet-redis#260]
## Environment
- **OS:**  Ubuntu 16.04
- **Redis version:**  4:4.0.8-1chl1~xenial1
  - Using the default ppa
- **Puppet module:**  the [add_redis_4_support](https://github.com/arioch/puppet-redis/tree/add_redis_4_support) branch
- **Puppet version**:  4.10.10

## Summary
When the service file is setup w/ `Type=forking`, I get timeouts, and the service continually restarts in a loop.

    Job for redis-server.service failed because a timeout was exceeded.

When I remove that setting (therefore using the default:  `Type=simple`), then it works as expected.

Why is that?  I assume it's because redis doesn't `call fork()` as part of its setup.
- Taken from http://manpages.ubuntu.com/manpages/xenial/en/man5/systemd.service.5.html#contenttoc4

For now, I'll have to workaround this by creating my own service file and the service.
- Passing `manage_service_file: false`

**Comment by dandunckelman** [comment]
Actually, the `manage_service_file` isn't a public class param.
- It's set by default to `false` in [params](https://github.com/arioch/puppet-redis/blob/add_redis_4_support/manifests/params.pp)
- It's set to `true` when `default_install: true`.

So, I'd have to set `default_install: false`, then repeat everything in https://github.com/arioch/puppet-redis/blob/add_redis_4_support/manifests/instance.pp just so I can change the content of the service file.

**Comment by ekohl** [comment]
In fce8da9c7b977db9f87e236cf63c2cb97abe8f93 daemonize behavior was improved to match the OS defaults. I believe with that this issue can be closed.

**Comment by dandunckelman** [comment]
Hilarious, I was just updating my Puppet stack and got bit by this again on v5.0.0.

Looks like it's fixed in https://github.com/voxpupuli/puppet-redis/commit/d779b75a937dd846323481e72eb604f5829e4c0e#diff-8845f76d702128044df189e2b992901e

I'll try that now.

**Comment by dandunckelman** [comment]
I just confirmed that the above commit fixed this.

This time, here are my environment details:
- OS: Ubuntu 18.04
- Redis server version: 5:5.0.7-1chl1~bionic1 (from http://ppa.launchpad.net/chris-lea/redis-server/ubuntu bionic/main)
- Puppet module: https://github.com/voxpupuli/puppet-redis/commit/d779b75a937dd846323481e72eb604f5829e4c0e
- Puppet version: 6.13.0

Thanks to everyone involved in making the updates to the service file!
