### ISSUE TITLE
Outdated dependency puppetlabs-apt < 3.0.0

### ISSUE THREAD

**Issue by llauren** [voxpupuli/puppet-redis#264]
Hi,

Would it be possible to update the dependency `puppetlabs-apt` to version &lt; 5? The current version seems to be 4.5.1 and this is blocking my forceless upgrade.

**Comment by petems** [comment]
This is already fixed on master but hasn't been released yet, let me do a release of 3.3.0 for the module

**Comment by petems** [comment]
Blocked by #267

**Comment by l-lotz** [comment]
I created #270 which updates the dependency to < 6.0.0

**Comment by walkamongus** [comment]
Can anyone confirm the module works with puppetlabs/apt 6.x.x? Would be good to bump compatibility to < 7.0.0 if it does.

**Comment by l-lotz** [comment]
According to the [Changelog](https://github.com/puppetlabs/puppetlabs-apt/blob/master/CHANGELOG.md#600-2018-08-24) puppetlabs/apt 6.0.0 removed support for puppet 4.7. I think if the dependency is updated to <7.0.0, this would also be a backward incompatible change for the redis module and require a version bump, right? Currently, however, there is no puppet version requirement specified in the metadata.json.

**Comment by alexjfisher** [comment]
Dependencies updated again in https://github.com/voxpupuli/puppet-redis/pull/296
Hopefully you can expect the a new release this week.
