### ISSUE TITLE
Update Redis administration $somaxconn value

### ISSUE THREAD

**Issue by kamusin** [voxpupuli/puppet-redis#271]
First of all, thank you for the awesome module you guys provide. Our company is doing the transition from our own in-house module to `puppet-redis`. I found today something that I figured a few months ago actually while reviewing our version and is related to the `net.core.somaxconn` kernel parameter. 

if you include `redis::administration`, one of the changes that we introduce to the kernel are setting `/proc/sys/net/core/sommax` to `65535`. regardless of the opportunity to alter this value, it doesn't affect much since [Redis](https://github.com/antirez/redis/blob/4.0.11/src/server.h) hardcodes this on the source code to `511`. You get a warning in the log file and then falls back to your limit in case is lower than that:

```
# tail /var/log/redis/redis.log 
30491:M 21 Aug 00:31:14.587 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.

# checking listen socket for Redis
root@ip-172-18-13-185:~# ss -lin | grep 6379
tcp    LISTEN     0      128       *:6379                  *:*
```

Depending of your Distro, the default value most of the times is `128` (at least for Ubuntu AMI's in AWS). We tuned our kernels based on the stack and some performance analysis, however for a base line we took that number from Brendan's Gregg [suggestion](http://www.brendangregg.com/blog/2015-03-03/performance-tuning-linux-instances-on-ec2.html).

**Comment by ekohl** [comment]
I'm not sure how to proceed here. It sounds like `redis::administration` is already doing what it's supposed to.

**Comment by ekohl** [comment]
Due to its age and that it needs feedback, I'm going to close this issue. If there's still a problem, please reopen or open a new issue/PR.
