### ISSUE TITLE
Module installation fails on Centos 7

### ISSUE THREAD

**Issue by fkoksal** [voxpupuli/puppet-redis#275]
When try to install the module (v3.3.0) on Centos 7 as described in module description
> puppet module install arioch-redis --version 3.3.0

I get the error below:
```
Error: Could not install module 'arioch-redis' (???)
  No version of 'arioch-redis' can satisfy all dependencies
    Use `puppet module install --ignore-dependencies` to install only this module
```

Module version: 3.3.0
Puppet version: 6.0.2
OS version: Centos 7

**Comment by ekohl** [comment]
We've moved to the Voxpupuli organization so I'm closing this now. Please reopen if this is still relevant with the latest release.
