### ISSUE TITLE
Please release v3.3.2 due to Ubuntu 18.04 / systemd fix.

### ISSUE THREAD

**Issue by crazymind1337** [voxpupuli/puppet-redis#283]
Hello,

the not yet existing version v.3.3.2 would fix an issue at our Ubuntu 18.04 setup. The service `redis-server.service` cannot be `enabled` at systemd due a misconfiguration, which has been fixed with commit 1c5e2d67827be409da8571ca335b01db66f17aa2. Please release v.3.3.2.

**Comment by fungunga** [comment]
Yes! Please do! :-) We also are waiting for it… Thanks a looooot!

**Comment by alexjfisher** [comment]
The module has been migrated to the Vox Pupuli community group and version 4.0.0 has just been released. https://forge.puppet.com/puppet/redis

**Comment by fungunga** [comment]
Yeah! Thanks! Works! Jippie!
