### ISSUE TITLE
Missing ability to secure sentinel?

### ISSUE THREAD

**Issue by ragingdave** [voxpupuli/puppet-redis#305]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.10
- Distribution: CentOS 7.6.1810
- Module version: 4.0
- Redis: >= 5.0.1

## How to reproduce (e.g Puppet code you use)
I mean  I don't have code but currently you can't configure the sentinel instances to requirepass to improve security in multi server redis instances managed by sentinel.

## What are you seeing
No security

## What behaviour did you expect instead
security via requirepass at the sentinel level

**Comment by alexjfisher** [comment]
The documentation could certainly be better, but I think this is already possible.
You can set [`auth_path`](https://github.com/voxpupuli/puppet-redis/blob/5464b335f9bd05fc0dd412bdd9dad97d4539a1f6/manifests/sentinel.pp#L168)  and that will configure sentinel [correctly](https://github.com/voxpupuli/puppet-redis/blob/5464b335f9bd05fc0dd412bdd9dad97d4539a1f6/templates/redis-sentinel.conf.erb#L13-L15).

The server also has the required parameters. See https://github.com/voxpupuli/puppet-redis/blob/5464b335f9bd05fc0dd412bdd9dad97d4539a1f6/manifests/init.pp#L208 https://github.com/voxpupuli/puppet-redis/blob/5464b335f9bd05fc0dd412bdd9dad97d4539a1f6/manifests/init.pp#L185

Hope this helps.

PRs that improve documentation always appreciated :)

**Comment by ragingdave** [comment]
This would (and correct me if I'm wrong) only enable sentinel to talk to a secure redis installation, not secure the communication between sentinel instances.

https://redis.io/topics/sentinel#configuring-sentinel-instances-with-authentication

This was added in Redis 5.0.1, so it's rather new.

**Comment by alexjfisher** [comment]
@ragingdave Ah, ok. I didn’t know about that. Thanks for the link. Would you be able to create a PR to add the functionality?

**Comment by ragingdave** [comment]
maybe.... I will see if I can tomorrow-nextweek-ish to put one through
