### ISSUE TITLE
Instance is not read from hiera file

### ISSUE THREAD

**Issue by lordbink** [voxpupuli/puppet-redis#329]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.10.1
- Ruby: 2.5.7p206 (default from bin directory inside puppet)
- Distribution: Ubuntu 16.04
- Module version: 4.2.1

## How to reproduce (e.g Puppet code you use)
This works inside nodes.pp:

```
 class { '::redis': }
 redis::instance {'test3':
   port => 1234,
 }
```

This does not work inside the node/hiera file (test-node.eyaml):

```
 redis::service_user: 'redis'
 redis::service_group: 'nogroup'
 redis::instance:
   'test3':
     enabled: true
     port: 1234
```

## What are you seeing
No changes to the end node and it appears to not see the configuration in hiera.

## What behaviour did you expect instead
Update to files inside the /etc/redis directory.

## Output log

> /etc/redis# puppet agent -t --certname test-redis.domain.com --noop
> Info: Using configured environment 'test_branch'
> Info: Retrieving pluginfacts
> Info: Retrieving plugin
> Info: Retrieving locales
> Info: Loading facts
> Info: Applying configuration version '1573688773'
> Notice: Applied catalog in 2.74 seconds

> ll
> total 88
> drwxr-xr-x   6 redis redis  4096 Nov 13 17:44 ./
> drwxr-xr-x 101 root  root   4096 Nov 13 14:56 ../
> -rw-r--r--   1 redis redis 32566 Nov 13 13:59 redis.conf
> -rw-r--r--   1 redis redis 32566 Nov 13 13:59 redis.conf.puppet
> drwxr-xr-x   2 root  root   4096 Nov 13 09:49 redis-server.post-down.d/
> drwxr-xr-x   2 root  root   4096 Nov 13 09:49 redis-server.post-up.d/
> drwxr-xr-x   2 root  root   4096 Nov 13 09:49 redis-server.pre-down.d/
> drwxr-xr-x   2 root  root   4096 Nov 13 09:49 redis-server.pre-up.d/

(nothing applied)

## Any additional information you'd like to impart
Let me know if there is anything I can add to be more helpful.

**Comment by Dan33l** [comment]
Hi @lordbink 

I am not user of this module. But, the resource `redis::instance` is a defined type. And so, it can not be used from hiera data.

One way to do this could be to implement a class `redis::instances` (endind with `s`) that call `redis::instance` (without `s`) via a `each` loop. Something like this  would make it possible to use hiera.

Can you propose a patch ?

**Comment by lordbink** [comment]
Pull request made: https://github.com/voxpupuli/puppet-redis/pull/330
