### ISSUE TITLE
Can't disable unixsocket after 

### ISSUE THREAD

**Issue by amoralej** [voxpupuli/puppet-redis#331]
After https://github.com/voxpupuli/puppet-redis/commit/502ff38c8c035fa143e32dd4ee61b3ec68db461c i can't disable unixsocket anymore.

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.10
- Ruby: ruby-2.0.0.648
- Distribution: centos7
- Module version: commit 5c97e7e4bbfe5238674ee80bf6d54b846d3802d5

## How to reproduce (e.g Puppet code you use)

class { '::redis':
  bind       => '127.0.0.1',
  appendonly => true,
  daemonize  => false,
  unixsocket => false,
}

Before the mentioned commit, setting unixsocket to false disabled unixsocket:
https://github.com/voxpupuli/puppet-redis/blob/master/templates/redis.conf.erb#L65-L70

## What are you seeing

Setting unixsocket to false fail because of parameter type, setting it to unset applies default value.

## What behaviour did you expect instead

Setting unixsocket to false should disable unix socket in redis.

## Output log

puppet apply --modulepath=/usr/share/openstack-puppet/modules --noop test.pp
Warning: Support for ruby version 2.0.0 is deprecated and will be removed in a future release. See https://puppet.com/docs/puppet/latest/system_requirements.html for a list of supported ruby versions.
   (location: /usr/share/ruby/vendor_ruby/puppet.rb:130:in `<module:Puppet>')
Warning: ModuleLoader: module 'redis' has unresolved dependencies - it will only see those that are resolved. Use 'puppet module list --tree' to see information about modules\n   (file & line not available)
Error: Evaluation Error: Error while evaluating a Resource Statement, Class[Redis]:
  parameter 'port' expects a Stdlib::Port::Unprivileged = Integer[1024, 65535] value, got Integer[777, 777]
  parameter 'unixsocket' expects a Stdlib::Absolutepath = Variant[Stdlib::Windowspath = Pattern[/^(([a-zA-Z]:[\\\/])|([\\\/][\\\/][^\\\/]+[\\\/][^\\\/]+)|([\\\/][\\\/]\?[\\\/][^\\\/]+))/], Stdlib::Unixpath = Pattern[/^\/([^\/\0]+\/*)*$/]] value, got Boolean (file: /root/test.pp, line: 1, column: 1) on node test4.example.com.rdocloud

**Comment by Dan33l** [comment]
Hi @amoralej thank you for this hi quality report.

First the parameter `unixsocket`, is described as `Define unix socket path`.
But the template uses `<% if @unixsocket %>unixsocket <%= @unixsocket %><% end %>`.
So yes, using `false` does not add `unixsocket` in the configuration file.

I am not sure it is an expected behavior, but we have to take care of this i suppose.
Perhaps a fix could be with a datatype like `Variant[Stdlib::Absolutepath, Boolean]` instead of Stdlib::Absolutepath.

I am not a user of this module, @ekohl or @alexjfisher any advice ?

**Comment by ekohl** [comment]
@amoralej thanks! Adding data types is tricky, but I do think it leads to a better module in the end.

What do you think about an empty string as a marker for the unix path?

Regarding the port: it looks like you're using 777 so I think we can start using `Stdlib::Port` instead.

**Comment by amoralej** [comment]
> @amoralej thanks! Adding data types is tricky, but I do think it leads to a better module in the end.
> 
> What do you think about an empty string as a marker for the unix path?
> 

I like more the idea of using Variant[Stdlib::Absolutepath, Boolean] as it'd maintain backwards compatibility but if you prefer to use empty string or other way, no problem.

> Regarding the port: it looks like you're using 777 so I think we can start using `Stdlib::Port` instead.

ups, you are right, i copied the error messages from a previous execution that also had 777 as port, but you can forget about that, was just a mistake. The relevant one is:

parameter 'unixsocket' expects a Stdlib::Absolutepath = Variant[Stdlib::Windowspath = Pattern[/^(([a-zA-Z]:[\/])|([\/][\/][^\/]+[\/][^\/]+)|([\/][\/]?[\/][^\/]+))/], Stdlib::Unixpath = Pattern[/^/([^/\0]+/)$/]] value, got Boolean (file: /root/test.pp, line: 1, column: 1) on node test4.example.com.rdocloud

**Comment by ekohl** [comment]
I've opened PRs for both issues. I'd appreciate reviews on them.

> I like more the idea of using Variant[Stdlib::Absolutepath, Boolean] as it'd maintain backwards compatibility but if you prefer to use empty string or other way, no problem.

https://github.com/voxpupuli/puppet-redis/pull/333

> ups, you are right, i copied the error messages from a previous execution that also had 777 as port, but you can forget about that, was just a mistake. The relevant one is:

https://github.com/voxpupuli/puppet-redis/pull/332
