### ISSUE TITLE
Redhat SCL Config_Dir Issue

### ISSUE THREAD

**Issue by jonra678** [voxpupuli/puppet-redis#341]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: v2018.1.11 (Enterprise)
- Ruby:
- Distribution: RHEL 7
- Module version: 5.0.0

## How to reproduce (e.g Puppet code you use)
Configure the module utilizing Redhat Software Collections implementation for Redis and Sentinel installation and configuration. This is after updating the globals.pp $scl variable from 'undef' to "rh-redis5" so RHSCL is leveraged. 

## What are you seeing
After attempting to install and configure Sentinel on Redis instances, the pathing for the redis-sentinel.conf file does not appear to be getting referenced by Sentinel. Overwriting properties within the redis::sentinel, log_file as an example, will not impact Sentinel configurations. Puppet will update the conf file properly, however the running Sentinel instance will not see these changes.

## What behaviour did you expect instead
Changes to the redis::sentinel class, without having to fully override the absolute path of the config_dir should apply to running instances of Sentinel.

## Output log
No logs that point this issue out, as on the surface it will appear to be a true configuration issue within your Redis/Sentinel setup.

## Any additional information you'd like to impart
We have resolved this issue internally by making the following code change. I believe one could also get around this by overriding the config_dir properties, however we felt that would lead to inconsistencies between the redis::sentinel and the redis classes and wanted a more cohesive/consistent solution. This puts all config files for both Redis and Redis Sentinel in the same location. 

Change description:
File: /redis/manifests/params.pp
Change line 60:
Old:  $config_dir                = "/etc/opt/rh/${scl}/redis"
New: $config_dir                = "/etc/opt/rh/${scl}"

**Comment by ekohl** [comment]
I must admit that when I wrote the SCL support code, I didn't look too carefully at the sentinel part and didn't write an acceptance tests for this. Since we don't use the sentinel, I don't think I'll have time to come up with a fix but a PR to address this would be very welcome and I'll gladly review it.
