### ISSUE TITLE
File descriptor limit is not set in systemd unit file by default. 

### ISSUE THREAD

**Issue by stasiek** [voxpupuli/puppet-redis#349]
## Affected Puppet, Ruby, OS and module versions/distributions
- Module version: 5.0

On a clean Debian installation /etc/security/limits.conf file descriptor limit can be set to whatever. When starting, Redis tries to ensure it can get 10k descriptors and crashes if it can't.

This module creates it's unit files for systemd, which is awesome, but there's no way to set the limit in the unit file which is how we should be doing in systemd-land.

So please can You make it possible to add `LimitNOFILE=` to the unit file below User and Group setting?

**Comment by ekohl** [comment]
https://github.com/voxpupuli/puppet-redis/issues/276 also reported this. Could you come up with a patch?

**Comment by ekohl** [comment]
Fixed in 0f930aad8cfed622b66ce522f2186b35de127165
