### ISSUE TITLE
Debian 10 dotdeb buster 

### ISSUE THREAD

**Issue by maxdwit** [voxpupuli/puppet-redis#361]
-  Puppet: 6.16
- Distribution: Debian 10.3
- Module version: puppet-redis (v5.0.1-rc0)

Info: /Stage[main]/Redis::Preinstall/Apt::Source[dotdeb]/Apt::Setting[list-dotdeb]/File[/etc/apt/sources.list.d/dotdeb.list]: Scheduling refresh of Class[Apt::Update]

## How to reproduce (e.g Puppet code you use)
puppet agent -t with redis module

## What are you seeing
dotdeb has no repository for buster

## What behaviour did you expect instead
dotdeb should be removed and/or fixed to contain the repository with the required deb files

## Output log
see error above

**Comment by ekohl** [comment]
Then you should not set `manage_repo` to true. This is off by default.

**Comment by and0x000** [comment]
Taking a look at the [dotdeb website](https://www.dotdeb.org/), it looks like this project has been discontinued in its entirety mid-2020. It might be worth discussing, if the dotdeb repository should be removed/replaced.

**Comment by ekohl** [comment]
Thanks for that info. I opened https://github.com/voxpupuli/puppet-redis/pull/371 to remove the code.
