### ISSUE TITLE
Systemd module is depreciated

### ISSUE THREAD

**Issue by lordbink** [voxpupuli/puppet-redis#442]
Are there any plans to replace the use of the cap-to-camp/systemd module? This module appears to be depreciated.

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: All
- Ruby: All
- Distribution: All
- Module version: Redis 8.2.0, Systemd 3.0.0

## How to reproduce (e.g Puppet code you use)
View logs when creating a new branch. Review systemd web page.

## What are you seeing
Systemd is depreciated.

## What behaviour did you expect instead
Systemd to not be depreciated

## Output log
WARN     -> Puppet Forge module 'camptocamp-systemd' has been deprecated, visit https://forge.puppet.com/camptocamp/systemd for more information.

## Any additional information you'd like to impart
This is for informational purposes and to see if there are any plans to replace systemd. Systemd and redis, in spite of the depreciation, will continue to function.

**Comment by lordbink** [comment]
It appears the voxpupuli systemd is the replacement:
https://github.com/voxpupuli/puppet-redis/pull/408

**Comment by smortex** [comment]
v8.0.0 switched to that module.
