### ISSUE TITLE
save_db_to_disk = false does not work

### ISSUE THREAD

**Issue by pankajr** [voxpupuli/puppet-redis#477]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 7
- Ruby: Not sure
- Distribution: RHEL7
- Module version: Latest

## How to reproduce (e.g Puppet code you use)
passing params `save_db_to_disk = false` does not make changes to the redis.conf file, instead it should add `save ""` to actually disable rdb writes to disk. To reproduce, set `save_db_to_disk = false` and disable aof. Redis still writes to disk at default interval.

## What are you seeing:
setting `save_db_to_disk = false` skips entries to redis.conf completely, defaulting redis to write to disk at default interval. 

## What behaviour did you expect instead
expected redis to skip writes altogether by making the entry `save ""` in the redis.conf file. 

## Any additional information you'd like to impart
No, its pretty straight forward

**Comment by jreilly650** [comment]
One other small detail...the existing behavior worked until redis 6.0, but in 6.2 the defaults changed making it necessary to generate `save ""`

**Comment by pankajr** [comment]
The above change is documented [here](https://raw.githubusercontent.com/redis/redis/6.2/redis.conf):
```
# Save the DB to disk.
#
# save <seconds> <changes>
#
# Redis will save the DB if both the given number of seconds and the given
# number of write operations against the DB occurred.
#
# Snapshotting can be completely disabled with a single empty string argument
# as in following example:
#
# save ""
#
# Unless specified otherwise, by default Redis will save the DB:
#   * After 3600 seconds (an hour) if at least 1 key changed
#   * After 300 seconds (5 minutes) if at least 100 keys changed
#   * After 60 seconds if at least 10000 keys changed
#
# You can set these explicitly by uncommenting the three following lines.
```
