### ISSUE TITLE
 The parameter '$slowlog_log_slower_than' must be a literal type, not a Puppet::Pops::Model::AccessExpression

### ISSUE THREAD

**Issue by trenta** [voxpupuli/puppet-redis#508]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 8.5.0
- Ruby:
- Distribution:
- Module version: 10.0.0

This started for me with the update to puppet 8.5.0. I get

Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: The parameter '$slowlog_log_slower_than' must be a literal type, not a Puppet::Pops::Model::AccessExpression (file: /etc/puppetlabs/code/environments/production/modules/redis/manifests/init.pp, line: 426, column: 15)

**Comment by C24-AK** [comment]
I had this problem too, see https://github.com/voxpupuli/puppet-redis/issues/500

**Comment by ekohl** [comment]
https://github.com/puppetlabs/puppet/issues/9268
