### ISSUE TITLE
Bind the service on all available interface

### ISSUE THREAD

**Issue by olbat** [voxpupuli/puppet-redis#60]
ATM it's not possible to disable the _bind_ parameter of the configuration file, it's also not possible to specify multiple binding address using the recipe. So if you want your server to listen to every available network interfaces, it's not possible ...

**Comment by jarshwah** [comment]
+1 to this. With later versions of redis you can specify multiple bind => "ipddr1 ipddr2".

**Comment by siliconalchemy** [comment]
You can do this to listen on all interfaces:
 bind => '0.0.0.0'

**Comment by olbat** [comment]
Okay, but that does not really solve the problem ...
Imagine that I have 4 network interfaces on my machine and I only want the service to be exposed on two of them.

**Comment by siliconalchemy** [comment]
Well it solves the issue you describe and the title of the issue, but yes it doesn't solve binding multiple selective interfaces, which would be a good enhancement.

**Comment by petems** [comment]
Ok, should be easy enough to implement, simply change the $bind variable to an array, loop through the array for multiple bindings 👍
