### ISSUE TITLE
If you install sentinel you are also running a redis instance

### ISSUE THREAD

**Issue by marcgascon** [voxpupuli/puppet-redis#84]
If you install sentinel you are also running a redis instance and you cannot parametrize it.

I think that you should be able to run only a redis (cluster, standalone, master-slaves) and/or a redis sentinel on the same/different instances. I'm going to do a PR to solve that. The target is that you will be able to choose:
- redis
- sentinel (without running a redis.)
- redis + sentinel

Bests,

**Comment by petems** [comment]
@marcgascon I'm not sure I understand. If you're using redis-sentinel, you require the redis binary to run, as it's just a simlink to the redis binary but running in sentinel mode? So if you're running sentinel, you're running redis.

**Comment by Caprico85** [comment]
> So if you're running sentinel, you're running redis.

That's correct. But this module starts a redis instance in sentinel mode **and a normal redis instance**.

```
$ ps aux | grep redis
redis    20140  0.0  0.0  51280  2248 ?        Ssl  11:55   0:00 /usr/bin/redis-server 127.0.0.1:6379
redis    20243  0.2  0.0  51280  3556 ?        Ssl  11:55   0:00 /usr/bin/redis-sentinel 0.0.0.0:26379 [sentinel]
```

In my case I only want to run Sentinel. I don't want a normal redis instance on this host. But the normal instance is enabled in `environments/production/modules/redis/manifests/service.pp` and there seems to be no way to disable it.

**Comment by petems** [comment]
Ah ok. 

In that case, you can specify that you want the standard redis service not to run:

```puppet
class { '::redis':
   service_ensure => 'stopped',
   # or service_manage => false,
}

class { '::redis::sentinel':
  master_name      => 'cow',
  redis_host       => '192.168.1.5',
  failover_timeout => 30000,
}
```

**Comment by Caprico85** [comment]
I already tried with various parameters on the sentinel instance itself. But I never thought about simply defining an additional instance. Thank you so much!

**Comment by ekohl** [comment]
Additionally `default_install` as a parameter can be used.
