### ISSUE TITLE
bind $ipaddress

### ISSUE THREAD

**Issue by atomicdata** [voxpupuli/puppet-redis#94]
I'm new to Puppet, so I apologize in advance if I am not doing something correctly.  I'm attempting to use the module through Puppet Enterprise.  I'd like to deploy a Redis cluster to several nodes and am attempting to make the bind variable map to $ipaddress in the Node Management console in Enterprise.

When I do this, the module installs as bind 127.0.0.1 in redis.conf.  If I perform an "rpm -e redis" on the node, then re-run puppet-agent -t on the node, it will correct the bind variable in redis.conf to the real IP address.  The problem is that after I do this, I can no longer start redis.  Just looking for guidance.

Thanks!

**Comment by bostrowski13** [comment]
You may want to use the facts hash to get the correct IP.

$facts[networking][ip]
